apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: projeto2
  labels:
    app: projeto2
spec:
  to:
    kind: Service
    name: projeto2
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
