apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-demo-hom
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LucianoRed/monorepo-gitops-demo.git
    targetRevision: HEAD
    path: config/departamentos/sub-departamento/projeto1
  destination:
    server: https://kubernetes.default.svc
    namespace: app-demo-hom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
